### ISSUE TITLE
VM Stat command

### ISSUE THREAD

**Issue by TheCodingPianoman** [hukl/macos-toolbox#1]
Potentially there is a mistake in the mentioned command. In section "System Statistics" the command is listed as `vmstat` but it is actually called `vm_stat`.
Additionally the possibility to pass an interval for continuous repetitions and a maximum repetition count could be mentioned, e.g. it is valid to write:
`vm_stat 10` to continuously print stats every 10 seconds or
`vm_stat -c 5 10` in order to print stats every 10 seconds but stop after five repetitions.

**Comment by hukl** [comment]
fixed it :)
